site_name: Data Delen Armoede en Schulden (DDAS)
site_description: De koppelvlakspecificatie voor de Data Delen Armoede en Schulden (DDAS) API
site_author: Arjen Brienen
site_url: https://www.divosa.nl/projecten/data-delen-over-armoede-en-schulden
theme:
  language: nl # (1)!
#  name: material
  name: readthedocs
extra:
  version: 0.0.1

nav:
  - Home: abstract.md
  - Uitgangspunten: uitgangspunten.md
  - Transportlaag: transport.md
  - Identificatie & Authenticatie: iam.md
  - Signing & Encryptie: signing-encryptie.md
  - Berichten: berichten.md
  - Niet functionele eisen: non-functionals.md
  - Aanleverprotocol: aanleverprotocol.md
  - Aansluitprotocol: aansluitprotocol.md
  - Beheer specificatie: beheer-specificatie.md

markdown_extensions:
#  - pymdownx.superfences
#  - pymdownx.inlinehilite
#  - pymdownx.tilde
#  - pymdownx.critic
#  - pymdownx.mark
#  - pymdownx.tasklist
#  - pymdownx.details
#  - pymdownx.tabbed:
#      alternate_style: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.highlight
#  - pymdownx.caret
#  - pymdownx.magiclink
#  - markdown_include.include:
#      base_path: docs

extra_css:
#  - stylesheets/extra.css

plugins:
#  - mike:
      # These fields are all optional; the defaults are as below...
#      alias_type: symlink
#      redirect_template: null
#      deploy_prefix: ''
#      canonical_version: 'latest'
#      version_selector: true
#      css_dir: css
#      javascript_dir: js
