name: Documentation CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "docs/**"

  pull_request:
    paths:
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    uses: Logius-standaarden/Automatisering/.github/workflows/build.yml@main

  check:
    needs: build
    name: Check
    uses: Logius-standaarden/Automatisering/.github/workflows/check.yml@main

  prepare-pdf:
    needs:
      - build
      - check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: static
          path: static

      - name: Install puppeteer
        run: |
          npm init -y
          npm install puppeteer

      - name: Download Logius PDF script
        run: |
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/pdf.js

      - name: Generate PDF
        run: |
          python3 -m http.server 8080 &
          sleep 5
          node pdf.js http://localhost:8080/static/index.html

      - name: Move PDF into site
        run: |
          mv *.pdf static/

      - name: Upload updated artifact
        uses: actions/upload-artifact@v4
        with:
          name: static
          path: static

  publish:
    needs:
      - prepare-pdf
    name: Publish (Logius)
    uses: Logius-standaarden/Automatisering/.github/workflows/publish.yml@main
    secrets: inherit
