name: Documentation CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "docs/**"

  pull_request:
    paths:
      - "docs/**"

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: Logius-standaarden/Automatisering/.github/workflows/build.yml@main

  check:
    needs: build
    name: Check
    uses: Logius-standaarden/Automatisering/.github/workflows/check.yml@main

  publish:
    needs:
      - build
      - check
    name: Publish (Logius)
    uses: Logius-standaarden/Automatisering/.github/workflows/publish.yml@main
    secrets: inherit
