name: Build and publish specification

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build site with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site

      - name: Install puppeteer
        run: |
          npm init -y
          npm install puppeteer

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Start server
        run: |
          python3 -m http.server 8080 --directory _site &
          sleep 5

      - name: Generate PDF
        run: |
          export PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
          node js/pdf.js http://localhost:8080/docs/index.html

      - name: Fix permissions
        run: |
          sudo chmod -R 777 _site

      - name: Move PDF into site
        run: |
          mv *.pdf _site/

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site


  publish:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
